### ISSUE TITLE
使わないのであれば変数に入れる意味がない

### ISSUE THREAD

**Issue by newburu** [newburu/RailsApp#2]
https://github.com/newburu/RailsApp/blob/416fc87f7c4bfcab60a1e3398b5612c452e83198/app/controllers/energys_controller.rb#L10

**Comment by RairuDev** [comment]
こちら下の行でインスタンス変数にして使っています。本当はメソッドに引数を持たせたいのですがそこで
def index(@graph_sort: "1週間")
このような形にできなかったため
仕方なくまず変数としてつくってそのあとインスタンス変数として代入してる形です

**Comment by RairuDev** [comment]
def index(graph_sort: "1週間")
graph_sort = params[:graph_sort] if params[:graph_sort]
@graph_sort = graph_sort

これを
def index
@graph_sort = params[:graph_sort].present? ? params[:graph_sort] :  "1週間"
こうしたらできました😳

**Comment by newburu** [comment]
他のところでも同じようにしてる所があったよー

**Comment by RairuDev** [comment]
有難うございます
listアクションのところもなおしました😎
