### ISSUE TITLE
変数名には意味を持たせた方が良い。@today等

### ISSUE THREAD

**Issue by newburu** [newburu/RailsApp#4]
https://github.com/newburu/RailsApp/blob/416fc87f7c4bfcab60a1e3398b5612c452e83198/app/controllers/energys_controller.rb?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L23

**Comment by RairuDev** [comment]
直しました〜
